covoiturageadmin:
    resource: "@covoiturageadminBundle/Resources/config/routing.yml"
    prefix:   /

covoiturageuser:
    resource: "@covoiturageuserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
